# Generated by Django 4.2.8 on 2026-01-16 17:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('investment_type', models.CharField(choices=[('ETF', 'ETF'), ('MUTUAL_FUND', 'Mutual Fund'), ('BOND', 'Bond'), ('EQUITY', 'Equity'), ('INDEX', 'Index Fund')], max_length=20)),
                ('description', models.TextField()),
                ('expected_return', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('liquidity', models.CharField(max_length=20)),
                ('reason', models.TextField(help_text='Why this is a good alternative')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('available_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('invested_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_risk_per_trade', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('VERY_LOW', 'Very Low (<0.5%)'), ('LOW', 'Low (0.5%-1%)'), ('MODERATE', 'Moderate (1%-2%)'), ('HIGH', 'High (2%-3%)'), ('VERY_HIGH', 'Very High (>3%)')], max_length=20)),
                ('risk_percentage', models.FloatField()),
                ('volatility_score', models.FloatField(help_text='0-100 volatility score')),
                ('liquidity_score', models.FloatField(help_text='0-100 liquidity score')),
                ('market_condition_score', models.FloatField(help_text='0-100 market condition score')),
                ('max_position_size', models.IntegerField(help_text='Maximum shares to buy')),
                ('recommended_stop_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assessment_notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('market_cap_category', models.CharField(choices=[('LARGE_CAP', 'Large Cap (>50B)'), ('MID_CAP', 'Mid Cap (5B-50B)'), ('SMALL_CAP', 'Small Cap (500M-5B)'), ('MICRO_CAP', 'Micro Cap (<500M)')], max_length=20)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('previous_close', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='StockAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('support_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resistance_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rsi', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('bollinger_upper', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bollinger_middle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bollinger_lower', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vwap', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sma_20', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sma_50', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sma_200', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ema_12', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ema_26', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('trend', models.CharField(choices=[('STRONG_BULLISH', 'Strong Bullish'), ('BULLISH', 'Bullish'), ('NEUTRAL', 'Neutral'), ('BEARISH', 'Bearish'), ('STRONG_BEARISH', 'Strong Bearish')], max_length=20)),
                ('trend_probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('volume', models.BigIntegerField()),
                ('average_volume_20', models.BigIntegerField()),
                ('volume_trend', models.CharField(choices=[('INCREASING', 'Increasing'), ('DECREASING', 'Decreasing'), ('STABLE', 'Stable')], max_length=20)),
                ('fib_0_236', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fib_0_382', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fib_0_500', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fib_0_618', models.DecimalField(decimal_places=2, max_digits=10)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='trading.stock')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_style', models.CharField(choices=[('INTRADAY', 'Intraday'), ('SWING', 'Swing'), ('POSITIONAL', 'Positional'), ('LONG_TERM', 'Long-Term')], max_length=20)),
                ('signal', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold'), ('AVOID', 'Avoid')], max_length=20)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_2', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('target_3', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('target_4', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('risk_percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('profit_percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('risk_reward_ratio', models.FloatField()),
                ('confidence_level', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('win_probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('valid_from_session', models.CharField(blank=True, max_length=50)),
                ('valid_until_session', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.stockanalysis')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='trading.stock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_entry_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('PARTIAL', 'Partially Executed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('profit_loss_percent', models.FloatField(null=True)),
                ('capital_allocated', models.DecimalField(decimal_places=2, max_digits=12)),
                ('risk_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='trading.traderecommendation')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trading.stock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['symbol'], name='trading_sto_symbol_a737b0_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['market_cap_category'], name='trading_sto_market__4a1096_idx'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='recommendation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='trading.traderecommendation'),
        ),
        migrations.AddField(
            model_name='alternativeinvestment',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='trading.traderecommendation'),
        ),
        migrations.AddIndex(
            model_name='traderecommendation',
            index=models.Index(fields=['stock', '-created_at'], name='trading_tra_stock_i_986ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='traderecommendation',
            index=models.Index(fields=['signal'], name='trading_tra_signal_4823c5_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeorder',
            index=models.Index(fields=['stock', '-created_at'], name='trading_tra_stock_i_a5fa74_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeorder',
            index=models.Index(fields=['status'], name='trading_tra_status_5012fd_idx'),
        ),
    ]
