# Generated by Django 4.2.8 on 2026-01-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_advanced_features'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiexplanation',
            new_name='trading_aie_related_261b59_idx',
            old_name='trading_aie_related_idx',
        ),
        migrations.RenameIndex(
            model_name='aiexplanation',
            new_name='trading_aie_explana_ec30df_idx',
            old_name='trading_aie_explanation_type_idx',
        ),
        migrations.RenameIndex(
            model_name='marketsummary',
            new_name='trading_mar_market__54a3cd_idx',
            old_name='trading_mar_market_date_idx',
        ),
        migrations.RenameIndex(
            model_name='papertrade',
            new_name='trading_pap_portfol_68aaa3_idx',
            old_name='trading_pap_portfol_idx',
        ),
        migrations.RenameIndex(
            model_name='papertrade',
            new_name='trading_pap_status_5b0e97_idx',
            old_name='trading_pap_status_idx',
        ),
        migrations.RenameIndex(
            model_name='smartalert',
            new_name='trading_sma_stock_i_f8bb5e_idx',
            old_name='trading_sma_stock_idx',
        ),
        migrations.RenameIndex(
            model_name='smartalert',
            new_name='trading_sma_alert_t_c331ac_idx',
            old_name='trading_sma_alert_type_idx',
        ),
        migrations.RenameIndex(
            model_name='tradingmistake',
            new_name='trading_tra_trade_o_a1afdf_idx',
            old_name='trading_tra_trade_order_idx',
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='market_date',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
